spring:
  application:
    name: direct-view
server:
  port: 8555
google:
  api:
    key: xxxxx
    opformat: json
  sv:
    image:
      width: 600
      height: 300
      pitch: 10
download:
  folder:
    path: C:\\Users\\Manu\\Desktop\\GSV
